feedback/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('form.urls')),
    path('admin/', admin.site.urls),
]

form/urls.py
from django.urls import path

from . import views

app_name = 'form'
urlpatterns = [
    path('', views.feedback_form, name='home'),
]

form/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    customer_name = models.CharField(max_length=120)
    email = models.EmailField()
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    details = models.TextField()
    happy = models.BooleanField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.customer_name


# Create your models here.

form/forms.py
from django import forms

from .models import Feedback


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        exclude = []

form/views.py
from django.shortcuts import render

from .forms import FeedbackForm


def feedback_form(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)

        if form.is_valid():
            form.save()
            return render(request, "thanks.html")
    else:
        form = FeedbackForm()
    return render(request, "feedback_form.html", {'form': form})

# Create your views here.

form/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>
    <style>
    body{
        font-family: Arial, Helvetica, sans-serif;
      }
      *{
        box-sizing: border-box;
      }
      h1{
        text-align: center;
        padding-top: 15px;
      }
      label {
        padding: 5px 12px 5px 0;
        display: inline-block;
        }
      input[type = text],
      input[type= email], input[type= checkbox], select, textarea{
        width: 40%;
        padding: 7px ;
        margin: 5px 0 22px 0;
        display: inline-block;
        border-radius: 7px;
      }
      input[type=text]:focus, input[type=email]:focus{
        background-color: blanchedalmond;
        outline: none;
      }
      input[type=submit] {
        background-color: #6d98c8;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        float: right;
        }

        input[type=submit]:hover {
        background-color: #6c7a8c;
        }

        .container {
        border-radius: 5px;
        background-color: #f2f2f2;
        padding: 20px;
        }
      
      /* hr{
        border: 1px solid white;
        margin-bottom: 25px;
      } */

      button:hover{
        opacity: 1px;
      }

    </style>
    {% block css %}     
    {% endblock css %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

form/templates/feedback_form.html
{% extends 'base.html' %}

{% block title %}Feedback Form{% endblock %}

{% block css %}
{% endblock css %}

{% block body %}
<h1>Feedback Form</h1>
<form action="{% url 'form:home' %}" method="POST">
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        <input type="submit" />
    </div>
    
</form>
{% endblock %}

form/templates/thanks.html
{% extends 'base.html' %}

{% block title %}Thanks{% endblock %}

{% block body %}
<br>
<h1>Thanks for your response.</h1>
<p><a href="{% url 'form:home' %}">Response again?</a></p>
{% endblock %}